### ISSUE TITLE
ValueError: could not convert string to float: ''

### ISSUE THREAD

**Issue by marrip** [BieseckerLab/SomatoSim#1]
Hey,

I am very interested in using SomatoSim for some testing data, however, I run into the above mentioned error during the tutorial. I was running

```
somatosim -i test_data/test_BAM.bam -b test_data/test_BED.bed -o ./output_dir --vaf-low 0.01 --vaf-high 0.05 --number-snv 100 --random-seed 0
```

and I got:

```
  ____                        _       ____  _
 / ___|  ___  _ __ ___   __ _| |_ ___/ ___|(_)_ __ ___
 \___ \ / _ \| '_ ` _ \ / _` | __/ _ \___ \| | '_ ` _ \
  ___) | (_) | | | | | | (_| | || (_) |__) | | | | | | |
 |____/ \___/|_| |_| |_|\__,_|\__\___/____/|_|_| |_| |_|

Tue Aug 10 11:23:03 2021

SomatoSim version 1.0.0
Python version 3.8.5
Numpy version 1.19.5
Pandas version 1.2.1
Matplotlib version 3.4.2
Pysam version 0.16.0.1
Samtools version 1.11

Started simulation run:
-----------------------
User inputs:
BAM file path: test_data/test_BAM.bam
BED file path: test_data/test_BED.bed
BED file input contains no pre-defined VAF or alternate allele

VAF range: 0.01 - 0.05
Output directory: ./output_dir
Using default output prefix
Number of positions to mutate: 100
Random seed: 0
Samtools mpileup coverage calculation using mapping quality (MQ) = 20 and base quality (BQ) = 20
Minimum base pair separation = 1
Verbose mode: Off

Started variant selection stage:
--------------------------------
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/somatosim_fn/main_fn.py", line 278, in variant_selection
    attempt = str(float(avgcov_value))
ValueError: could not convert string to float: '289,784'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/bin/somatosim", line 67, in <module>
    main_fn.variant_selection(args.arg_input_bam_file,
  File "/opt/miniconda3/lib/python3.8/site-packages/somatosim_fn/main_fn.py", line 287, in variant_selection
    attempt = str(float(avgcov_value))
ValueError: could not convert string to float: ''
```

Is it possibly a version hickup? I am using newer versions for all dependencies as you can see. Any help or feedback would be highly appreciated. 😊

**Comment by marwanhawari** [comment]
Hi,

This is an issue of EU vs US decimal points. I'm working on getting this resolved.

**Comment by Leehyeonjin93** [comment]
Hi,
I got same problem.
Was not resolved yet?

**Comment by marwanhawari** [comment]
I've created a Docker image for SomatoSim here: https://hub.docker.com/r/marwanhawari/somatosim
I'd recommend using the Docker image for now because it looks like the issue has to do with one of the dependencies.

**Comment by Leehyeonjin93** [comment]
thank you.
I used a docker image.
But I had a other error massage.
I was running : 
`docker run -it -v /data/project/08.NA12878/NA12878/NA12878_T_WES/01.preprocessing/02.BQSR:/mnt  marwanhawari/somatosim -i /mnt/NA12878_T_WES_dup_recal.bam -b /mnt/TCGA_34_5239_01A_21D_1817_08.snv_true.bed -o /mnt`

and I got :
```
Using input BED format

Average coverage of original BAM file: nan

Started selecting positions for simulation
Traceback (most recent call last):
  File "/usr/local/bin/somatosim", line 67, in <module>
    main_fn.variant_selection(args.arg_input_bam_file,
  File "/usr/local/lib/python3.8/site-packages/somatosim_fn/main_fn.py", line 433, in variant_selection
    rando = int(selected_range[int(random_position_tracker[k])])
IndexError: index 0 is out of bounds for axis 0 with size 0
```

bed region : `chr1    216086725       216086725       0.35    A`

bam example : 
![image](https://user-images.githubusercontent.com/40356335/178444487-393419d1-f933-4d2a-a149-6fb1d8feeb8d.png)

I tried using other bam files, but I got a same error massage.
